{{- $path := "/" .Values.fullnameOverride "/client-api(/|$)(.*)" -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mock-bot.fullname" . }}-ingress
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ include "mock-bot.fullname" . }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /client-api/$2
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: letsencrypt-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
        paths:
          - path: {{ default $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "mock-bot.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}